---
abstract: 'Map::Metro map for Stockholm'
author:
  - 'Erik Carlsson <info@code301.com>'
build_requires:
  Test::NoTabs: '0'
configure_requires:
  Module::Build::Tiny: '0.039'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Map-Metro-Plugin-Map-Stockholm
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Map::Metro: '0.1800'
  perl: '5.020000'
version: '0.1965'
